descript x-ray and ct preprocessing in readme and change util
Hitdahit/Code_Refactoring pull request #46
Opened 2022-03-26 06:42 UTC by ccd4565

1. X-ray와 CT slices 전처리 과정 readme에 작성했습니다.
2. util에서 X-ray의 min-max scaling과 percentile 전처리 함수에 MONOCHROME 관련 전처리 추가 했습니다.
3. X-ray와 CT slices 전처리 함수 전부에 0~1로 먼저 normalize 시키고 그 다음에 pixel 값이 1을 넘거나 0을 못 넘는 값들에 대해 threshold를 시켰습니다.

2022-03-27 05:59 UTC, Hitdahit requested changes
util.py
pixel_array_image min.max scaling을 진행할 때 dicom 파일의 BitsStored로 max 값을 정한 이유가 있을까요?? 꼭 BitStored로 2를 제곱한 수가 이미지의 max value인지 확인해야 할 것 같습니다.

README.md
간략하게 정리해주셔서 감사합니다. 추후에 영어가 어색한 부분은 제가 수정할 수 있습니다.
또한, 추후에 한글 버전을 부탁드리게 될 수 있습니다ㅠ

2022-03-30 01:56 UTC, ccd4565 commented
1. BitStored가 dataset에서 dicom image의 bit수가 다른 경우를 대비해서 0~1로 normalize 시켜주는 과정인데 CT는 HU가 정해져 있어서 BitStored 전처리는 제외했는데 X-ray 아직 잘 모르겠어서 남겨뒀습니다. 이 부분은 다같이 얘기해보면 좋을 것 같습니다.
2. CT 전처리에서 input을 windowing 처리를 하고 모델에 넣는 경우를 추가했습니다. 이에 따라서 함수의 명령인자에 window_width와 window_level을 default값 None으로 추가했습니다. 이 부분은 arg.parser에 추가가 필요할 것 같습니다.

2022-03-30 04:10 UTC, Hitdahit commented
1. Bitstored는 다같이 논의해보는게 좋을 것 같습니다.
2. window_width, window_height default 값이 None인 것은 좋지 않을 것 같습니다.
   Bone, lung, stomach 등을 위한 값들은 모두 정해져 있는 것으로 아는데 디폴트 값을 특정해두는 것이 좋을 것 같습니다. args에 해당 내용은 추가하도록 하겠습니다.

2022-04-04 04:38 UTC, Hitdahit commented
1. X-ray는 max 값을 np.max로 하면 된단다.
2. CT는 HU때문에 BitsStored를 max값으로 취하면 된단다.
알겠니?

2022-04-10 07:36 UTC, Hitdahit commented
두가지 수정 완료 하셨나요?

2022-04-10 07:43 UTC, Hitdahit requested changes
전체적으로 사용하시는 값들과 수식에 대한 주석을 요청드립니다.

그외에 필수적이지 않다고 생각되는 부분들이 몇몇 있는데 이번주에 시간 괜찮으시면 같이 봐야 할 것 같습니다.

짜두신 코드에 대해서 명확한 근거가 있다면 유지하고 아니면 고칠 방향을 수립하는 방식으로 진행하겠습니다.

2022-04-10 07:43 UTC, Hitdahit commented on util.py
> +def CT_preprocess(data, image_size, window_width=None, window_level=None):
이렇게 인자 추가해주는거 좋습니다.
시간나실 때  함수 안에 주석치고 매개변수 설명 추가해주시면 감사드리겠습니다.

2022-04-10 07:43 UTC, Hitdahit commented on util.py
>      pixel_array_image[np.where(pixel_array_image < image_min)] = image_min
이미지의 min, max 값을 찾아서 0, 1로 만드려는 코드인가요?

어차피 min max scaling 식에 의해 자동으로 0, 1이 되는 것으로 알고 있는데 사용하시는 이유가 따로 있을까요?

2022-04-10 07:43 UTC, Hitdahit commented on util.py
> +    if dicom_image.PhotometricInterpretation == 'MONOCHROME1':
MONOCHROME1 description 추가 부탁드려요

2022-04-10 07:43 UTC, Hitdahit commented on util.py
> +    pixel_array_image[np.where(pixel_array_image < image_min)] = image_min
위랑 같은 코멘트 입니다. 이유가 있으시면 알려주세요~

2022-04-10 07:43 UTC, Hitdahit commented on util.py
>      slope = dicom_image.RescaleSlope
intercept, slope도 설명 적어주세요

2022-04-10 08:27 UTC, ccd4565 commented on util.py
> +def CT_preprocess(data, image_size, window_width=None, window_level=None):
매게 변수 설명 추가했습니다.

2022-04-10 08:27 UTC, ccd4565 commented on util.py
>      pixel_array_image[np.where(pixel_array_image < image_min)] = image_min
min max scaling에서는 따로 안 해줘도 될 것 같습니다. 제거하겠습니다.

2022-04-10 08:27 UTC, ccd4565 commented on util.py
> +    if dicom_image.PhotometricInterpretation == 'MONOCHROME1':
설명 보강해서 추가했습니다.

2022-04-10 08:27 UTC, ccd4565 commented on util.py
> +    pixel_array_image[np.where(pixel_array_image < image_min)] = image_min
percentile 99로 친 이유는 x-ray 영상에서 가끔식 LR 마크의 intensity가 다른 부분에 비해 압도적으로 클 떄가 있는데 그 문제를 해결하고자 LR 마크 다음으로 intensity가 높은 값으로 min max scaling을 치고 LR 마크를 1.0으로 내리는 과정입니다. min값 threshold는 혹시 몰라서 추가 했습니다.

2022-04-10 08:27 UTC, ccd4565 commented on util.py
>      slope = dicom_image.RescaleSlope
intercept, slope는 뭔가 말로 표현하기 어려워서 강제 전처리 task라고만 일단 해놨습니다.

2022-04-11 03:14 UTC, Hitdahit commented on util.py
>      pixel_array_image[np.where(pixel_array_image < image_min)] = image_min
엇 저는 그 밑의 np.where 부분을 말씀드린 것이긴 한데요;;

2022-04-11 03:14 UTC, Hitdahit commented on util.py
> +    if dicom_image.PhotometricInterpretation == 'MONOCHROME1':
MONOCHROME1이 무엇인지도 써주실 수 있나요?

2022-04-11 03:18 UTC, Hitdahit commented on util.py
> +    pixel_array_image[np.where(pixel_array_image < image_min)] = image_min
음... 실제로 저 thresholding을 하지 않으면 처리되지 않는 경우가 있나요??

2022-04-11 04:03 UTC, ccd4565 commented on util.py
>      pixel_array_image[np.where(pixel_array_image < image_min)] = image_min
네 그 부분 맞아요. min max scaling에 의해서 0,1이 되니까 필요 없는 부분이라 제거했습니다.

2022-04-11 04:04 UTC, ccd4565 commented on util.py
> +    if dicom_image.PhotometricInterpretation == 'MONOCHROME1':
그것도 써놨습니다. 이거 push가 제대로 안 되고 있는걸까요. 확인 해봐야겠네요

2022-04-11 04:05 UTC, ccd4565 commented on util.py
> +    pixel_array_image[np.where(pixel_array_image < image_min)] = image_min
LR 마크 다음으로 높은 값을 max로 잡기 때문에 LR 마크가 1보다 크게 됩니다. 그걸 1로 강제로 내리는 과정입니다. 아니면 percentile도 명령 인자 값으로 주게끔 할까요?

2022-04-11 06:10 UTC, Hitdahit commented
고생하셨습니다 머지합니다

2022-04-11 06:10 UTC, merged